### ISSUE TITLE
Using nashgore with Smooth Doom and BLUDTYPE patch causes imp fireballs to flicker in mid-air

### ISSUE THREAD

**Issue by PopeRigby** [nashmuhandes/nashgore#6]
I recorded some [footage](https://imgur.com/GZjO9SO) of it happening.

**Comment by nashmuhandes** [comment]
This commit was supposed to fix the sprite name clashing: https://github.com/nashmuhandes/nashgore/commit/063b02a01697c25b79c6567a2a6a1787aa0deef5

**Comment by PopeRigby** [comment]
I'm on the latest version, so I guess it didn't?

**Comment by nashmuhandes** [comment]
You'll have to download this repo to see the changes. :P The ModDB file is at version 1.0, which hasn't been updated yet. The next official release will have this fix, whenever that is done.

I am going to close this issue because it technically has already been fixed (just checked with Smooth Doom five minutes ago, in fact).
